### ISSUE TITLE
Resource temporarily unavailable while building in MacOS

### ISSUE THREAD

**Issue by achakrab** [hyrise/hyrise#1914]
$$ make hyriseConsole -j
Got the following errors:

[ 76%] Building CXX object src/lib/CMakeFiles/hyrise.dir/statistics/base_attribute_statistics.cpp.o
[ 76%] Building CXX object src/lib/CMakeFiles/hyrise.dir/statistics/cardinality_estimator.cpp.o
clang-9: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
clang-9: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
make[3]: *** [src/lib/CMakeFiles/hyrise.dir/statistics/abstract_cardinality_estimator.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [src/lib/CMakeFiles/hyrise.dir/statistics/base_attribute_statistics.cpp.o] Error 1
[ 76%] Building CXX object src/lib/CMakeFiles/hyrise.dir/statistics/generate_pruning_statistics.cpp.o
/bin/sh: fork: Resource temporarily unavailable

Any quick fix for this one? 

-Thanks

**Comment by mrks** [comment]
Try reducing the number of parallel build tasks (`make ... -j 10`).

**Comment by achakrab** [comment]
Thanks. Now, getting  this new error:
hyrise/src/lib/utils/string_utils.hpp:16:58: error: 'path' is unavailable: introduced in macOS
      10.15
std::string plugin_name_from_path(const std::filesystem::path& path);

**Comment by mrks** [comment]
Yepp, the Apple toolchain is no fun to work with. We decided against spending time trying to support older OS X versions. If upgrading is not an option for you, maybe a slightly older version of Hyrise (38fc8642 from two weeks ago) works for you. If you let us know what you are interested in, we might be able to find a solution.

**Comment by achakrab** [comment]
Getting the same error after upgrading to 10.15.1. Xcode appears to be up-to-date. Any other steps to follow? Thanks,

**Comment by mrks** [comment]
Did you clear the build folder and re-run cmake after the upgrade? I believe cmake does not recognize a new OS X version and does not reset the isysroot arguments.

We have been using `filesystem::path` for months on 10.14 - I don't understand why the upgrade to llvm-9 suddenly broke that. [Looks like we are not alone](https://stackoverflow.com/questions/58648316/does-llvm-9-support-stdfilesystem-on-versions-of-the-mac-prior-to-10-15?noredirect=1&lq=1), though.

**Comment by achakrab** [comment]
Cleaning up the  build folder resolved the issue.

Got the following error after plain "cmake ..": 
Apple's clang compiler is not supported because it is lacking support for
  recent C++ features.  Please run cmake with
  `-DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang
  -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++`.  You can ignore this
  error by setting -DENABLE_UNSUPPORTED_COMPILER=ON.
Call Stack (most recent call first):
  CMakeLists.txt:37 (compiler_not_supported)

built with:
cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang 
 -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++  ..

**Comment by mrks** [comment]
Yes, that is expected. Do I understand you correctly that you are now able to build and run Hyrise?

Also, please keep in mind that the `cmake` command that you posted gives you an unoptimized debug build with additional checks. `-DCMAKE_BUILD_TYPE=Release` gives you a release build with better performance.

**Comment by achakrab** [comment]
Yes, I could build and run. Is there any command to create/show database? I saw only "show tables/views".

**Comment by mrks** [comment]
We do not support multiple databases / schemas yet, as those are largely uninteresting from a research perspective. Thus, you do not need to create/select a database before you create a table.
