### ISSUE TITLE
Hyrise server fails to build with boost 1.66

### ISSUE THREAD

**Issue by adi64** [hyrise/hyrise#859]
It looks like boost now includes functionality that was backported and shipped with hyrise?
```
[  5%] Building CXX object src/lib/CMakeFiles/hyrise.dir/server/client_connection.cpp.o
In file included from /opt/hyrise/src/lib/server/use_boost_future.hpp:68:0,
                 from /opt/hyrise/src/lib/server/client_connection.cpp:7:
/opt/hyrise/src/lib/server/use_boost_future_impl.hpp:19:7: error: redeclared with 1 template parameter
 class promise_handler {
       ^~~~~~~~~~~~~~~
In file included from /usr/include/boost/asio/use_future.hpp:156:0,
                 from /usr/include/boost/asio.hpp:131,
                 from /opt/hyrise/src/lib/server/client_connection.cpp:3:
/usr/include/boost/asio/impl/use_future.hpp:590:7: note: previous declaration ‘template<class Signature, class Allocator> class boost::asio::detail::promise_handler’ used 2 template parameters
 class promise_handler
       ^~~~~~~~~~~~~~~
...
```
Full build log: https://pastebin.com/7pKDT3nb

Paging @lawben

**Comment by lawben** [comment]
I'll have a look. Where are you building this? On your machine, which OS?

**Comment by adi64** [comment]
yep, my machine. ArchLinux x64, kernel 4.16.3, boost 1.66.0, gcc 7.3.1

**Comment by lawben** [comment]
I really hate dependency management. Our CI still uses boost 1.63, newest Ubuntu version is 1.65, newest OSX version is 1.67...

I think I have a fix. PR coming in a sec.

**Comment by lawben** [comment]
@adi64 If this is is currently blocking you, you can just apply the changes to the [`promise_handler`](https://github.com/hyrise/hyrise/blob/9c31a8de5462699ee9d9a2c5b60ece84bc5f9ed0/src/lib/server/use_boost_future_impl.hpp#L19) (i.e. change to `boost_promise_handler`)

**Comment by adi64** [comment]
Works for me. Thanks! :+1:
