### PR TITLE
Fix boost version for server

### LINKED ISSUE #859: Hyrise server fails to build with boost 1.66
It looks like boost now includes functionality that was backported and shipped with hyrise?
```
[  5%] Building CXX object src/lib/CMakeFiles/hyrise.dir/server/client_connection.cpp.o
In file included from /opt/hyrise/src/lib/server/use_boost_future.hpp:68:0,
                 from /opt/hyrise/src/lib/server/client_connection.cpp:7:
/opt/hyrise/src/lib/server/use_boost_future_impl.hpp:19:7: error: redeclared with 1 template parameter
 class promise_handler {
       ^~~~~~~~~~~~~~~
In file included from /usr/include/boost/asio/use_future.hpp:156:0,
                 from /usr/include/boost/asio.hpp:131,
                 from /opt/hyrise/src/lib/server/client_connection.cpp:3:
/usr/include/boost/asio/impl/use_future.hpp:590:7: note: previous declaration ‘template<class Signature, class Allocator> class boost::asio::detail::promise_handler’ used 2 template parameters
 class promise_handler
       ^~~~~~~~~~~~~~~
...
```
Full build log: https://pastebin.com/7pKDT3nb

Paging @lawben

### PR DESCRIPTION
**Pull request by lawben**
- Fixes #859.
- Updates the Docker image to Ubuntu Bionic (18.04)
- Sets the minimum required boost version to 1.65

@mrks How can we update the Docker image in CI? I updated the Dockerfile but it did not pick up the changes.

Still WIP, because I need to verify these changes really go through in CI and not just locally.

I can't add @adi64 as a reviewer. Does he still need to be added to the list?

### CODE REVIEW

**Comment by Bensk1** [comment]
To update the docker image used for CI take a look at: https://github.com/hyrise/hyrise/blob/master/Jenkinsfile
