### PR TITLE
Upgrade Ubuntu, clang, and boost

### LINKED ISSUE #758: clang-format@3.8 is no longer available via homebrew
The formula for `clang-format@3.8` has recently been [removed](https://github.com/Homebrew/homebrew-core/pull/23083) from brew for macOS.
We should update our install readme accordingly.

### LINKED ISSUE #859: Hyrise server fails to build with boost 1.66
It looks like boost now includes functionality that was backported and shipped with hyrise?
```
[  5%] Building CXX object src/lib/CMakeFiles/hyrise.dir/server/client_connection.cpp.o
In file included from /opt/hyrise/src/lib/server/use_boost_future.hpp:68:0,
                 from /opt/hyrise/src/lib/server/client_connection.cpp:7:
/opt/hyrise/src/lib/server/use_boost_future_impl.hpp:19:7: error: redeclared with 1 template parameter
 class promise_handler {
       ^~~~~~~~~~~~~~~
In file included from /usr/include/boost/asio/use_future.hpp:156:0,
                 from /usr/include/boost/asio.hpp:131,
                 from /opt/hyrise/src/lib/server/client_connection.cpp:3:
/usr/include/boost/asio/impl/use_future.hpp:590:7: note: previous declaration ‘template<class Signature, class Allocator> class boost::asio::detail::promise_handler’ used 2 template parameters
 class promise_handler
       ^~~~~~~~~~~~~~~
...
```
Full build log: https://pastebin.com/7pKDT3nb

Paging @lawben

### PR DESCRIPTION
**Pull request by mrks**
This updates a couple of things and gets rid of hacky stuff in the install script. fixes #859 (thanks @lawben), fixes #758. Also, I fixed some issues with the install script on a clean OS X without any dev tools.

Please check out this branch, make sure that you can still build Hyrise, and approve this PR.

### CODE REVIEW

File: CMakeLists.txt [hunk 1]
```diff
@@ -72,7 +75,7 @@ set(CURSES_NEED_NCURSES TRUE)
 # Dependencies
 find_package(FS REQUIRED)
 find_package(Numa)
-find_package(LLVM 5.0.0)
```
Comment (mrks) [inline CMakeLists.txt]: @jfrohnhofen - This does not cause and tests to fail, even if we use LLVM 6. Is this valid?

**Comment by Bouncner** [comment]
```➜  cm git:(mrks/update-versions) cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++  -DCMAKE_BUILD_TYPE=Debug ..
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang
-- Check for working C compiler: /usr/local/opt/llvm/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++
-- Check for working CXX compiler: /usr/local/opt/llvm/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found C++ stdlib filesystem library: lib=/usr/local/Cellar/llvm/6.0.0/lib/libc++experimental.a
-- WARNING: Numa library not found.
-- Try: 'sudo yum install numactl numactl-devel' (or sudo apt-get install libnuma libnuma-dev)
-- Found tbb library: inc=/usr/local/include, lib=/usr/local/lib/libtbb.dylib
-- Found readline library: inc=/usr/local/opt/readline/include, lib=/usr/local/opt/readline/lib/libreadline.dylib
-- Looking for wsyncup in /usr/lib/libcurses.dylib
-- Looking for wsyncup in /usr/lib/libcurses.dylib - found
-- Looking for cbreak in /usr/lib/libncurses.dylib
-- Looking for cbreak in /usr/lib/libncurses.dylib - found
-- Found Curses: /usr/lib/libncurses.dylib
-- Found sqlite3 library: inc=/usr/include, lib=/usr/lib/libsqlite3.dylib
-- WARING: pq library not found.
-- Try: 'sudo yum install libpq-dev' (or sudo apt-get install libpq-dev)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- Found llvm library: inc=/usr/local/opt/llvm/include, lib=/usr/local/opt/llvm/lib/libLLVM.dylib
-- Found PythonInterp: /usr/local/bin/python (found version "3.6.5")
-- Building with JIT support
-- Building without NUMA support
-- The ASM compiler identification is Clang
-- Found assembler: /usr/local/opt/llvm/bin/clang
-- Adding operators/jit_operator/jit_operations.cpp to LLVM bundle
-- Adding operators/jit_operator/jit_operations.hpp to LLVM bundle
-- Adding operators/jit_operator/jit_types.cpp to LLVM bundle
-- Adding operators/jit_operator/jit_types.hpp to LLVM bundle
-- Adding operators/jit_operator/operators/abstract_jittable.hpp to LLVM bundle
-- Adding operators/jit_operator/operators/abstract_jittable_sink.hpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_compute.cpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_compute.hpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_expression.cpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_expression.hpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_filter.cpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_filter.hpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_read_tuple.cpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_read_tuple.hpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_write_tuple.cpp to LLVM bundle
-- Adding operators/jit_operator/operators/jit_write_tuple.hpp to LLVM bundle
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/Users/martin/Programming/tmp_Opossum_mrks/third_party/PQ_INCLUDE_DIR
   used as include directory in directory /Users/martin/Programming/tmp_Opossum_mrks/third_party

-- Configuring incomplete, errors occurred!
See also "/Users/martin/Programming/tmp_Opossum_mrks/cm/CMakeFiles/CMakeOutput.log".
```

**Comment by mrks** [comment]
`git submodule update --init --recursive`? That's not something from this PR.

**Comment by Bouncner** [comment]
Schon gemacht, alles aktuell.

**Comment by mrks** [comment]
Ah. `brew install libpq`. Ist auch schon älter.

File: CMakeLists.txt (hunk 1 above)
Comment (jfrohnhofen) [reply CMakeLists.txt]: It may very well be. I would expect the LLVM apis to be pretty stable.
If this causes any trouble in the following PRs or in the future in general, we should adapt/migrate the Jitting to LLVM 6 anyway.

**Comment by Bensk1** [comment]
Does this also mean that we have to upgrade the images on our servers like pella, side, and nemea?

**Comment by mrzzzrm** [comment]
Does this mean Ubuntu 18.04 becomes the one and only supported Ubuntu version? Just checking, feel like I am not keeping up with upgrading my machines...

Also, please do not break pella support, Moritz needs that.

**Comment by mrks** [comment]
If you have your system set up now, you will not need to change anything. Same goes for pella.

With this PR, fresh installations would only support 18.04.

File: CMakeLists.txt (hunk 1 above)
Comment (FabianWiebe) [reply CMakeLists.txt]: Yes, the files `CloneFunction.cpp` and `InlineFunction.cpp` from JIT PR 5 #813 will not compile with LLVM6 as they use unofficial apis from LLVM5.

Comment (mrks) [reply CMakeLists.txt]: Good thing that we notice that now. @FabianWiebe - do you already have enough insight to see what needs to change?

Comment (FabianWiebe) [reply CMakeLists.txt]: Yes, we need to take the new versions for LLVM6 of `CloneFunction.cpp` and `InlineFunction.cpp` from https://github.com/llvm-mirror/llvm/tree/release_60/lib/Transforms/Utils and adjust them to Hyrise, again.

Comment (mrks) [reply CMakeLists.txt]: Could you get started on that, please?

Comment (FabianWiebe) [reply CMakeLists.txt]: Yes.

**Comment by Bensk1** [comment]
Should we use that opportunity to upgrade to gcc 8.1 as well?

File: CMakeLists.txt (hunk 1 above)
Comment (jfrohnhofen) [reply CMakeLists.txt]: @mrks @FabianWiebe Do you intend to support multiple LLVM versions for jitting in parallel? That sound like maintenance hell to me...
If we require LLVM 6 for jitting moving forward `find_package(LLVM 6.0.0 CONFIG)` should be added and the CI systems would need to be upgraded to LLVM 6.

Comment (mrks) [reply CMakeLists.txt]: Will do.

Comment (FabianWiebe) [reply CMakeLists.txt]: @jfrohnhofen No, I would only support one.
